#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hongtan.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Hongtan")]
	public partial class CandidateModelDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertEditApplyModel(EditApplyModel instance);
    partial void UpdateEditApplyModel(EditApplyModel instance);
    partial void DeleteEditApplyModel(EditApplyModel instance);
    partial void InsertCandidateModel(CandidateModel instance);
    partial void UpdateCandidateModel(CandidateModel instance);
    partial void DeleteCandidateModel(CandidateModel instance);
    #endregion
		
		public CandidateModelDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["HongtanConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CandidateModelDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CandidateModelDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CandidateModelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CandidateModelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<EditApplyModel> EditApplyModel
		{
			get
			{
				return this.GetTable<EditApplyModel>();
			}
		}
		
		public System.Data.Linq.Table<CandidateModel> CandidateModel
		{
			get
			{
				return this.GetTable<CandidateModel>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Hongtan_EditApply")]
	public partial class EditApplyModel : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _RelatedCandidateId;
		
		private string _ApplyReason;
		
		private string _ApplierTel;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnRelatedCandidateIdChanging(int value);
    partial void OnRelatedCandidateIdChanged();
    partial void OnApplyReasonChanging(string value);
    partial void OnApplyReasonChanged();
    partial void OnApplierTelChanging(string value);
    partial void OnApplierTelChanged();
    #endregion
		
		public EditApplyModel()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RelatedCandidateId", DbType="INT")]
		public int RelatedCandidateId
		{
			get
			{
				return this._RelatedCandidateId;
			}
			set
			{
				if ((this._RelatedCandidateId != value))
				{
					this.OnRelatedCandidateIdChanging(value);
					this.SendPropertyChanging();
					this._RelatedCandidateId = value;
					this.SendPropertyChanged("RelatedCandidateId");
					this.OnRelatedCandidateIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplyReason", CanBeNull=false)]
		public string ApplyReason
		{
			get
			{
				return this._ApplyReason;
			}
			set
			{
				if ((this._ApplyReason != value))
				{
					this.OnApplyReasonChanging(value);
					this.SendPropertyChanging();
					this._ApplyReason = value;
					this.SendPropertyChanged("ApplyReason");
					this.OnApplyReasonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplierTel", CanBeNull=false)]
		public string ApplierTel
		{
			get
			{
				return this._ApplierTel;
			}
			set
			{
				if ((this._ApplierTel != value))
				{
					this.OnApplierTelChanging(value);
					this.SendPropertyChanging();
					this._ApplierTel = value;
					this.SendPropertyChanged("ApplierTel");
					this.OnApplierTelChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Hongtan_Candidate")]
	public partial class CandidateModel : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Name;
		
		private string _Department;
		
		private string _Role;
		
		private string _Introduction;
		
		private string _Tel;
		
		private string _Story;
		
		private System.Nullable<int> _BidCount;
		
		private int _BidAdjust;
		
		private int _Hidden;
		
		private System.Nullable<int> _Priority;
		
		private System.Nullable<int> _Type;
		
		private bool _SeemsDuplicate;
		
		private string _Submitter;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnDepartmentChanging(string value);
    partial void OnDepartmentChanged();
    partial void OnRoleChanging(string value);
    partial void OnRoleChanged();
    partial void OnIntroductionChanging(string value);
    partial void OnIntroductionChanged();
    partial void OnTelChanging(string value);
    partial void OnTelChanged();
    partial void OnStoryChanging(string value);
    partial void OnStoryChanged();
    partial void OnBidCountChanging(System.Nullable<int> value);
    partial void OnBidCountChanged();
    partial void OnBidAdjustChanging(int value);
    partial void OnBidAdjustChanged();
    partial void OnHiddenChanging(int value);
    partial void OnHiddenChanged();
    partial void OnPriorityChanging(System.Nullable<int> value);
    partial void OnPriorityChanged();
    partial void OnTypeChanging(System.Nullable<int> value);
    partial void OnTypeChanged();
    partial void OnSeemsDuplicateChanging(bool value);
    partial void OnSeemsDuplicateChanged();
    partial void OnSubmitterChanging(string value);
    partial void OnSubmitterChanged();
    #endregion
		
		public CandidateModel()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Department", DbType="NVarChar(10)")]
		public string Department
		{
			get
			{
				return this._Department;
			}
			set
			{
				if ((this._Department != value))
				{
					this.OnDepartmentChanging(value);
					this.SendPropertyChanging();
					this._Department = value;
					this.SendPropertyChanged("Department");
					this.OnDepartmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Role", DbType="NVarChar(10)")]
		public string Role
		{
			get
			{
				return this._Role;
			}
			set
			{
				if ((this._Role != value))
				{
					this.OnRoleChanging(value);
					this.SendPropertyChanging();
					this._Role = value;
					this.SendPropertyChanged("Role");
					this.OnRoleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Introduction", DbType="NVarChar(50)")]
		public string Introduction
		{
			get
			{
				return this._Introduction;
			}
			set
			{
				if ((this._Introduction != value))
				{
					this.OnIntroductionChanging(value);
					this.SendPropertyChanging();
					this._Introduction = value;
					this.SendPropertyChanged("Introduction");
					this.OnIntroductionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tel", DbType="NVarChar(20)")]
		public string Tel
		{
			get
			{
				return this._Tel;
			}
			set
			{
				if ((this._Tel != value))
				{
					this.OnTelChanging(value);
					this.SendPropertyChanging();
					this._Tel = value;
					this.SendPropertyChanged("Tel");
					this.OnTelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Story", DbType="NVarChar(MAX)")]
		public string Story
		{
			get
			{
				return this._Story;
			}
			set
			{
				if ((this._Story != value))
				{
					this.OnStoryChanging(value);
					this.SendPropertyChanging();
					this._Story = value;
					this.SendPropertyChanged("Story");
					this.OnStoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BidCount", DbType="Int")]
		public System.Nullable<int> BidCount
		{
			get
			{
				return this._BidCount;
			}
			set
			{
				if ((this._BidCount != value))
				{
					this.OnBidCountChanging(value);
					this.SendPropertyChanging();
					this._BidCount = value;
					this.SendPropertyChanged("BidCount");
					this.OnBidCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BidAdjust", DbType="Int NOT NULL")]
		public int BidAdjust
		{
			get
			{
				return this._BidAdjust;
			}
			set
			{
				if ((this._BidAdjust != value))
				{
					this.OnBidAdjustChanging(value);
					this.SendPropertyChanging();
					this._BidAdjust = value;
					this.SendPropertyChanged("BidAdjust");
					this.OnBidAdjustChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hidden", DbType="Int NOT NULL")]
		public int Hidden
		{
			get
			{
				return this._Hidden;
			}
			set
			{
				if ((this._Hidden != value))
				{
					this.OnHiddenChanging(value);
					this.SendPropertyChanging();
					this._Hidden = value;
					this.SendPropertyChanged("Hidden");
					this.OnHiddenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Priority", DbType="Int")]
		public System.Nullable<int> Priority
		{
			get
			{
				return this._Priority;
			}
			set
			{
				if ((this._Priority != value))
				{
					this.OnPriorityChanging(value);
					this.SendPropertyChanging();
					this._Priority = value;
					this.SendPropertyChanged("Priority");
					this.OnPriorityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="Int")]
		public System.Nullable<int> Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SeemsDuplicate", DbType="Bit NOT NULL")]
		public bool SeemsDuplicate
		{
			get
			{
				return this._SeemsDuplicate;
			}
			set
			{
				if ((this._SeemsDuplicate != value))
				{
					this.OnSeemsDuplicateChanging(value);
					this.SendPropertyChanging();
					this._SeemsDuplicate = value;
					this.SendPropertyChanged("SeemsDuplicate");
					this.OnSeemsDuplicateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Submitter", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Submitter
		{
			get
			{
				return this._Submitter;
			}
			set
			{
				if ((this._Submitter != value))
				{
					this.OnSubmitterChanging(value);
					this.SendPropertyChanging();
					this._Submitter = value;
					this.SendPropertyChanged("Submitter");
					this.OnSubmitterChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
